/**
 * The email template catalogue: categories, subcategories and the original
 * copy each one is written from. The generator (generateTemplates.ts) combines
 * these with layouts, palettes and typography; nothing here is rendered as-is.
 *
 * To add templates, add a subcategory (or a category) below and re-run
 * `npm run email:seed`. Existing templates are left untouched.
 */

export type Archetype =
  | "newsletter"
  | "promo"
  | "product"
  | "transactional"
  | "event"
  | "announcement"
  | "listing";

/** An occasion that re-themes a subcategory (e.g. a festival or season). */
export interface ThemeDef {
  name: string;
  tags: string[];
  headline: string;
  /** Palette keys that suit the occasion; the generator prefers these. */
  palettes?: string[];
}

export interface SubcategoryDef {
  slug: string;
  name: string;
  archetype: Archetype;
  tags: string[];
  headlines: string[];
  subs: string[];
  ctas: string[];
  /** [title, text] pairs used for articles, features, products or agenda rows */
  items: [string, string][];
  /** [label, value] rows for event details, order summaries and similar */
  details?: [string, string][];
  themes?: ThemeDef[];
}

export interface CategoryDef {
  slug: string;
  name: string;
  description: string;
  /** Fictional wordmarks used as the placeholder logo */
  brands: string[];
  prices: string[];
  subs: SubcategoryDef[];
}

function sub(
  slug: string,
  name: string,
  archetype: Archetype,
  tags: string,
  headlines: string[],
  subs: string[],
  ctas: string[],
  items: string[],
  extra: { details?: string[]; themes?: ThemeDef[] } = {}
): SubcategoryDef {
  const pair = (value: string): [string, string] => {
    const at = value.indexOf(": ");
    return at === -1 ? [value, ""] : [value.slice(0, at), value.slice(at + 2)];
  };
  return {
    slug, name, archetype, tags: tags.split(",").map((t) => t.trim()).filter(Boolean), headlines, subs, ctas,
    items: items.map(pair), details: extra.details?.map(pair), themes: extra.themes,
  };
}

export const OCCASIONS: ThemeDef[] = [
  { name: "Diwali", tags: ["diwali", "festival of lights", "festival", "india"], headline: "Light up the season this Diwali", palettes: ["saffron", "onyx", "plum", "ember"] },
  { name: "Christmas", tags: ["christmas", "holiday", "xmas", "festive"], headline: "Make this Christmas one to remember", palettes: ["emerald", "ember", "forest", "coral"] },
  { name: "New Year", tags: ["new year", "nye", "celebration"], headline: "Ring in the New Year in style", palettes: ["onyx", "midnight", "cobalt", "aubergine"] },
  { name: "Eid", tags: ["eid", "eid mubarak", "festival", "ramadan"], headline: "Eid Mubarak: celebrate together", palettes: ["emerald", "onyx", "teal", "sand"] },
  { name: "Holi", tags: ["holi", "festival of colours", "festival", "spring"], headline: "Celebrate Holi in full colour", palettes: ["citrus", "rose", "plum", "coral"] },
  { name: "Lunar New Year", tags: ["lunar new year", "chinese new year", "spring festival"], headline: "Welcome the Lunar New Year", palettes: ["ember", "onyx", "coral", "saffron"] },
  { name: "Thanksgiving", tags: ["thanksgiving", "autumn", "gratitude"], headline: "Gather round this Thanksgiving", palettes: ["clay", "saffron", "sand", "ember"] },
  { name: "Halloween", tags: ["halloween", "spooky", "october"], headline: "A frightfully good Halloween", palettes: ["ember", "aubergine", "onyx", "saffron"] },
  { name: "Easter", tags: ["easter", "spring", "holiday"], headline: "Hop into Easter", palettes: ["mint", "rose", "citrus", "sky"] },
  { name: "Hanukkah", tags: ["hanukkah", "festival of lights", "holiday"], headline: "Eight nights of light", palettes: ["cobalt", "midnight", "sky", "arctic"] },
  { name: "Valentine's Day", tags: ["valentines", "love", "february", "romance"], headline: "Made with love for Valentine's Day", palettes: ["rose", "coral", "ember", "plum"] },
  { name: "Mother's Day", tags: ["mothers day", "mum", "gift"], headline: "For the mums who do it all", palettes: ["rose", "mint", "sand", "plum"] },
  { name: "Black Friday", tags: ["black friday", "cyber monday", "deals"], headline: "Black Friday starts now", palettes: ["onyx", "ink", "midnight", "ember"] },
  { name: "Summer", tags: ["summer", "season", "sunshine"], headline: "Hello, summer", palettes: ["citrus", "sky", "coral", "teal"] },
  { name: "Winter", tags: ["winter", "season", "cosy"], headline: "Winter warmers are here", palettes: ["arctic", "slate", "midnight", "cobalt"] },
  { name: "Back to School", tags: ["back to school", "september", "students"], headline: "Ready for the new term", palettes: ["cobalt", "citrus", "sky", "mint"] },
];

export const EMAIL_CATEGORIES: CategoryDef[] = [
  {
    slug: "business", name: "Business", description: "Company news, updates and professional communication",
    brands: ["ALDERLINE", "BRIGHTWELL & CO", "KESTREL GROUP", "HALDEN", "NORTHGATE PARTNERS", "MERRICK"],
    prices: ["$49", "$120", "$240", "$990"],
    subs: [
      sub("corporate-newsletter", "Corporate Newsletter", "newsletter", "newsletter, corporate, company news, monthly",
        ["This month at a glance", "The company briefing", "What we shipped, learned and planned"],
        ["A short read on the work, the people and the numbers that shaped our month.", "Everything worth knowing from across the business, in five minutes."],
        ["Read the full update", "See all stories"],
        ["A stronger quarter than forecast: Revenue grew across all three regions, led by renewals.", "New faces on the team: Seven colleagues joined us in product, finance and support.", "Customer story of the month: How one logistics team cut reporting time in half.", "Dates for your diary: Town hall, planning week and the autumn offsite."]),
      sub("company-announcement", "Company Announcement", "announcement", "announcement, news, press, company",
        ["An important update from our team", "Big news: a new chapter begins", "We have something to share"],
        ["Here is what is changing, why we are doing it and what it means for you.", "We wanted you to hear this from us first."],
        ["Read the announcement", "Learn what changes"],
        ["What is changing: A clear summary of the decision and when it takes effect.", "Why now: The reasoning behind the move and what we expect from it.", "What stays the same: Your account, your contacts and your pricing are unaffected.", "Where to ask questions: Our team is on hand all week to help."]),
      sub("internal-update", "Internal Update", "newsletter", "internal, team, staff, employee, update",
        ["Team update: the week ahead", "Inside the company this week", "Your Friday round-up"],
        ["Priorities, wins and reminders for everyone on the team.", "A quick sync so nobody has to dig through channels."],
        ["Open the team hub", "View the roadmap"],
        ["Priorities this week: Three goals every team is aligned on.", "Wins worth celebrating: Launches, renewals and kind words from customers.", "People news: Birthdays, anniversaries and new starters.", "Reminders: Expenses are due Friday and reviews open Monday."]),
      sub("executive-newsletter", "Executive Newsletter", "newsletter", "executive, leadership, ceo, letter, briefing",
        ["A note from the CEO", "Leadership briefing", "From the desk of our founder"],
        ["Reflections on the quarter and where we are steering next.", "A candid look at what is working, what is not and what comes next."],
        ["Read the full letter", "Watch the address"],
        ["Where we stand: The metrics that matter and how they moved.", "What we learned: Three lessons from our hardest project this year.", "Where we are going: Our priorities for the next two quarters.", "A thank you: To the teams who made the difference."]),
      sub("business-proposal", "Business Proposal", "announcement", "proposal, pitch, b2b, partnership, services",
        ["A proposal built around your goals", "Let's build this together", "Your tailored plan is ready"],
        ["We have outlined the scope, timeline and investment for your review.", "A clear plan, a fixed price and a team that has done this before."],
        ["Review the proposal", "Book a walkthrough"],
        ["Scope of work: Exactly what we will deliver in each phase.", "Timeline: Milestones from kickoff to launch in twelve weeks.", "Investment: Transparent pricing with no hidden extras.", "Why us: Relevant experience and references you can call."]),
      sub("investor-update", "Investor Update", "newsletter", "investor, shareholders, funding, metrics, startup",
        ["Investor update: quarterly highlights", "Our quarter in numbers", "Progress report for our investors"],
        ["Growth, runway and the milestones we hit since our last note.", "The good, the difficult and the asks."],
        ["View the full report", "Download the deck"],
        ["Headline metrics: Recurring revenue, retention and burn at a glance.", "Product progress: What shipped and what customers said.", "Hiring: Key roles filled and the ones still open.", "How you can help: Introductions that would move the needle."]),
      sub("product-announcement", "Product Announcement", "product", "product, announcement, release, new",
        ["Introducing our newest product", "It's here: meet the next generation", "Say hello to something new"],
        ["Designed from the ground up to save your team time.", "Faster, simpler and ready for the way you work today."],
        ["See what's new", "Get early access"],
        ["Built for speed: Everything loads instantly, even with large workspaces.", "Simple by design: A cleaner interface with fewer clicks.", "Works with your tools: Connect the apps you already rely on.", "Secure by default: Enterprise-grade protection on every plan."]),
      sub("welcome-onboarding", "Welcome & Onboarding", "announcement", "welcome, onboarding, getting started, new customer",
        ["Welcome aboard", "You're in. Let's get you set up", "Glad to have you with us"],
        ["Three quick steps and you will be up and running.", "Here is everything you need for a great first week."],
        ["Get started", "Complete your setup"],
        ["Step 1. Set up your profile: Add your details so your team can find you.", "Step 2. Invite your team: Collaboration is better with company.", "Step 3. Create your first project: Start from scratch or pick a template.", "Need a hand?: Our support team replies within the hour."]),
    ],
  },
  {
    slug: "marketing", name: "Marketing", description: "Launches, promotions and campaign emails",
    brands: ["LUMEN", "FIELD & FORM", "VANTA STUDIO", "OAKLEY LANE", "PIXELWORKS", "SOLSTICE"],
    prices: ["$19", "$35", "$59", "$129"],
    subs: [
      sub("product-launch", "Product Launch", "product", "launch, new product, release, introducing",
        ["The wait is over", "Launching today", "Meet the one you've been waiting for"],
        ["Our most requested product is finally here, and it is better than we promised.", "Be among the first to try it."],
        ["Shop the launch", "Explore the features"],
        ["Reimagined from scratch: Every detail reconsidered and refined.", "Made to last: Tested for years of everyday use.", "Yours in three colours: Pick the finish that suits you.", "Launch offer: Early buyers get free delivery."]),
      sub("sale", "Sale", "promo", "sale, offer, savings, deal",
        ["The big sale is on", "Up to 50% off everything", "Our biggest sale of the year"],
        ["Hundreds of favourites at prices you will not see again this season.", "Stock is limited and the best pieces go first."],
        ["Shop the sale", "See all offers"],
        ["Everyday essentials: The pieces you reach for most, reduced.", "Bestsellers: Customer favourites at their lowest price.", "Last chance: Final sizes and colours while they last.", "New markdowns: Fresh reductions added this morning."]),
      sub("promotion", "Promotion", "promo", "promotion, promo, offer, special, campaign",
        ["A little something, just for you", "This week only: an exclusive offer", "Your special offer inside"],
        ["Use your code at checkout before Sunday midnight.", "A thank you for being part of our community."],
        ["Claim your offer", "Redeem now"],
        ["Free delivery: On every order, no minimum spend.", "Gift with purchase: A full-size favourite with orders over $60.", "Double points: Earn twice the rewards all week.", "Bundle and save: Buy any two and save 20%."]),
      sub("discount", "Discount", "promo", "discount, coupon, code, percent off, voucher",
        ["Here's 20% off your next order", "Your discount code is waiting", "Save more when you shop today"],
        ["Enter the code at checkout. Valid on full-price items for seven days.", "No catches, no minimum spend."],
        ["Use my code", "Start shopping"],
        ["New arrivals: Fresh in this week and included in the offer.", "Top rated: The products customers review best.", "Under $50: Small prices, made smaller.", "Gift ideas: Thoughtful picks for every budget."]),
      sub("flash-sale", "Flash Sale", "promo", "flash sale, limited time, 24 hours, urgent, countdown",
        ["24 hours only", "Flash sale: ends at midnight", "Blink and you'll miss it"],
        ["Our fastest sale yet. When the clock runs out, the prices go back.", "Limited stock, limited time, serious savings."],
        ["Shop before midnight", "Grab the deal"],
        ["Hour one: Doorbuster prices on a handful of bestsellers.", "While stocks last: Once it is gone, it is gone.", "Extra 10% off: For orders placed before noon.", "Free returns: Changed your mind? No problem."]),
      sub("new-collection", "New Collection", "product", "collection, new arrivals, lookbook, season",
        ["The new collection has landed", "Fresh for the season", "New season, new favourites"],
        ["Considered shapes, natural materials and colours drawn from the coast.", "A capsule of pieces designed to be worn together."],
        ["Explore the collection", "View the lookbook"],
        ["The everyday jacket: Lightweight, lined and made to layer.", "The relaxed trouser: Cut for comfort without losing shape.", "The weekend bag: Roomy, structured and built to travel.", "The finishing touch: Accessories that pull a look together."]),
      sub("campaign", "Campaign", "announcement", "campaign, brand, awareness, story, movement",
        ["Join the movement", "This is what we stand for", "A campaign with a purpose"],
        ["A season-long project about doing things properly.", "We are asking a simple question, and we would love your answer."],
        ["Watch the film", "Get involved"],
        ["The idea: Why we started and what we want to change.", "The people: Meet the makers behind the work.", "The pledge: What we are committing to this year.", "Your part: Three simple ways to take part."]),
      sub("lead-generation", "Lead Generation", "announcement", "lead generation, ebook, download, guide, signup, b2b",
        ["Your free guide is ready", "Download the playbook", "The report everyone in your field is reading"],
        ["Forty pages of practical advice, benchmarks and templates you can use today.", "No fluff: just what worked for two hundred teams."],
        ["Download the guide", "Get my free copy"],
        ["Chapter 1. The benchmark: How you compare with teams your size.", "Chapter 2. The framework: A repeatable process in five steps.", "Chapter 3. The templates: Copy, paste and adapt.", "Bonus: A checklist to share with your team."]),
    ],
  },
  {
    slug: "ecommerce", name: "E-commerce", description: "Store, order and customer lifecycle emails",
    brands: ["MARLOW", "THE GOODS CO", "HEARTH & PINE", "JUNIPER SUPPLY", "FOLD", "CASA NOVA"],
    prices: ["$18", "$32", "$64", "$110"],
    subs: [
      sub("abandoned-cart", "Abandoned Cart", "promo", "abandoned cart, reminder, checkout, cart recovery",
        ["You left something behind", "Still thinking it over?", "Your cart misses you"],
        ["We have saved your items, but we cannot hold them for long.", "Complete your order today and delivery is on us."],
        ["Return to my cart", "Complete my order"],
        ["Saved for you: Your picks are reserved for the next 48 hours.", "Free delivery: Finish checking out today and shipping is free.", "Easy returns: Thirty days to change your mind.", "Need help deciding?: Chat with our team any time."]),
      sub("order-confirmation", "Order Confirmation", "transactional", "order confirmation, receipt, thank you, purchase",
        ["Thanks for your order", "Order confirmed", "We've got your order"],
        ["We are getting it ready now and will email you the moment it ships.", "Here is a summary of everything you bought."],
        ["View my order", "Track my order"],
        ["What happens next: We pack your order within one working day.", "Delivery: Expect it in two to four working days.", "Changed your mind?: You can amend the order for the next hour.", "Questions?: Reply to this email and a person will answer."],
        { details: ["Order number: #48213", "Order date: 14 March", "Payment: Card ending 4242", "Total: $128.00"] }),
      sub("shipping-update", "Shipping Update", "transactional", "shipping, delivery, tracking, dispatch, on its way",
        ["Your order is on its way", "Good news: it has shipped", "Out for delivery today"],
        ["Your parcel has left our warehouse. Follow it every step of the way.", "Track it live with the link below."],
        ["Track my parcel", "View delivery details"],
        ["Packed with care: Checked twice and wrapped without plastic.", "On the road: Handed to the courier this morning.", "Arriving soon: Estimated delivery in two days.", "Not home?: Choose a safe place or a new day."],
        { details: ["Tracking number: FX 2291 0047", "Courier: Swiftline Express", "Estimated delivery: Thursday", "Delivery address: 12 Market Street"] }),
      sub("product-recommendation", "Product Recommendation", "promo", "recommendation, picked for you, personalised, suggestions",
        ["Picked just for you", "We think you'll love these", "Because you liked that, try this"],
        ["Based on what you have browsed, here are a few things worth a look.", "Hand-picked by our team, not by an algorithm."],
        ["See my picks", "Shop recommendations"],
        ["Pairs well with your last order: The natural next step.", "Trending now: What everyone is adding to their basket.", "Back in stock: A favourite returns after selling out.", "Staff pick: The one our team keeps buying."]),
      sub("new-product", "New Product", "product", "new product, just in, new arrival, drop",
        ["Just dropped", "New in: you saw it here first", "Fresh on the shelves"],
        ["Small batch, carefully made and available from today.", "The newest addition to the range, and already a team favourite."],
        ["Shop new in", "Take a closer look"],
        ["Thoughtful materials: Sourced responsibly and built to age well.", "Made in small batches: When this run is gone, it is gone.", "Designed in-house: Sketched, sampled and tested by our team.", "Ready to ship: In stock and leaving the warehouse today."]),
      sub("seasonal-sale", "Seasonal Sale", "promo", "seasonal, sale, holiday, festive, offers",
        ["The seasonal sale starts now", "Seasonal savings are here", "Celebrate with our best prices"],
        ["Gifts, treats and favourites at prices worth celebrating.", "For a limited time, everything you need for the season is reduced."],
        ["Shop the sale", "Find the perfect gift"],
        ["Gifts under $25: Small gestures that mean a lot.", "For the home: Make the season feel special.", "For them: Presents they will actually use.", "Last order dates: Order by the 20th for guaranteed delivery."],
        { themes: OCCASIONS }),
      sub("customer-loyalty", "Customer Loyalty", "promo", "loyalty, rewards, points, vip, members",
        ["Your rewards are waiting", "You've unlocked VIP status", "A thank you for being a member"],
        ["You have earned enough points for a reward. Here is how to spend them.", "Members get first access, extra savings and a birthday treat."],
        ["See my rewards", "Redeem my points"],
        ["Your points balance: 1,240 points, enough for $12 off.", "Early access: Shop new collections a day before everyone else.", "Member pricing: Exclusive prices on selected lines.", "Birthday treat: A gift from us in your birthday month."]),
      sub("review-request", "Review Request", "transactional", "review, feedback, rating, survey, testimonial",
        ["How did we do?", "Tell us what you think", "Your opinion matters to us"],
        ["It takes two minutes and helps other customers choose with confidence.", "We read every review, good or bad."],
        ["Write a review", "Rate my order"],
        ["Quick and easy: Three questions, no account needed.", "Honest feedback: Tell us what we could do better.", "Help others: Your review guides future customers.", "A small thank you: 10% off your next order when you finish."],
        { details: ["Item: Linen throw, natural", "Ordered: 2 March", "Delivered: 6 March", "Order number: #47710"] }),
    ],
  },
  {
    slug: "events", name: "Events", description: "Invitations, reminders and celebrations",
    brands: ["THE GATHERING", "HARBOUR HALL", "ELM & IVY", "SUMMIT SERIES", "LANTERN EVENTS", "ROOFTOP SOCIAL"],
    prices: ["Free", "$25", "$79", "$199"],
    subs: [
      sub("wedding", "Wedding", "event", "wedding, save the date, marriage, rsvp, couple",
        ["Together with their families", "Save the date", "We're getting married"],
        ["We would be honoured to have you with us as we say I do.", "Join us for an afternoon of vows, dinner and dancing."],
        ["RSVP", "View wedding details"],
        ["The ceremony: Four o'clock in the walled garden.", "The reception: Dinner and speeches in the orangery.", "Staying over: Rooms held at two hotels nearby.", "Gifts: Your presence is the only present we need."],
        { details: ["Date: Saturday 14 June", "Time: 4:00 pm", "Venue: Ashcombe House", "Dress code: Formal"] }),
      sub("birthday", "Birthday", "event", "birthday, party, celebration, invite",
        ["You're invited to celebrate", "It's a birthday party", "Let's eat cake"],
        ["Good food, loud music and people we love. Come hungry.", "Another year older, and we are making a night of it."],
        ["I'll be there", "RSVP now"],
        ["Food and drinks: A full spread, with something for everyone.", "Music: A playlist of nothing but favourites.", "Bring: Just yourself and your dancing shoes.", "Running late?: The party goes on until midnight."],
        { details: ["Date: Friday 9 May", "Time: 7:30 pm", "Where: The Loft, 21 Canal Road", "RSVP by: 1 May"] }),
      sub("conference", "Conference", "event", "conference, summit, speakers, tickets, industry",
        ["Two days. Forty speakers. One room.", "The conference returns", "Registration is now open"],
        ["Talks, workshops and conversations with the people shaping the field.", "Early-bird tickets are available until the end of the month."],
        ["Get my ticket", "View the agenda"],
        ["09:00 Opening keynote: Where the industry goes from here.", "11:00 Practitioner panels: Lessons from teams doing the work.", "14:00 Hands-on workshops: Small groups, real problems.", "18:00 Evening social: Meet the speakers over drinks."],
        { details: ["Dates: 22 to 23 October", "Venue: Riverside Convention Centre", "Tickets: From $199", "Capacity: 800 attendees"] }),
      sub("webinar", "Webinar", "event", "webinar, online event, live session, register, virtual",
        ["Join our live webinar", "Free webinar: save your seat", "Learn it live in 45 minutes"],
        ["A practical session with time for your questions at the end.", "Cannot make it live? Register anyway and we will send the recording."],
        ["Save my seat", "Register free"],
        ["What you will learn: A framework you can apply the same day.", "Who is speaking: Two practitioners with a decade of experience.", "Live Q&A: Bring the questions you cannot search for.", "Recording included: Watch again whenever you like."],
        { details: ["Date: Wednesday 18 September", "Time: 4:00 pm GMT", "Length: 45 minutes", "Cost: Free"] }),
      sub("workshop", "Workshop", "event", "workshop, class, hands-on, training, learn",
        ["A hands-on workshop", "Learn by doing", "Small group. Big progress."],
        ["Spend a day building the skill with an expert by your side.", "Limited to twelve places so everyone gets attention."],
        ["Book my place", "See what's covered"],
        ["Morning: Foundations and guided exercises.", "Lunch: Included, with time to meet the group.", "Afternoon: Your own project with one-to-one feedback.", "Take home: Notes, templates and a certificate."],
        { details: ["Date: Saturday 5 April", "Time: 10:00 am to 4:00 pm", "Location: Studio 3, The Old Mill", "Price: $79"] }),
      sub("meetup", "Meetup", "event", "meetup, community, networking, local, casual",
        ["This month's meetup", "Come say hello", "Pizza, talks and good company"],
        ["Two short talks, then plenty of time to chat. First-timers very welcome.", "An easy evening with people who care about the same things."],
        ["Count me in", "See who's coming"],
        ["Doors at six: Grab a drink and find a seat.", "Talk one: A story from the field in ten minutes.", "Talk two: A live demo, risks and all.", "Afterwards: We head next door until late."],
        { details: ["Date: Thursday 12 June", "Time: 6:00 pm", "Venue: The Workshop, 8 Bridge Lane", "Entry: Free"] }),
      sub("festival", "Festival", "event", "festival, celebration, cultural, holiday, community",
        ["Celebrate with us", "Join the festivities", "A celebration for everyone"],
        ["Music, food and tradition, shared with friends and family.", "Bring the whole family for an evening of light, colour and joy."],
        ["Join the celebration", "See the programme"],
        ["Music and dance: Live performances throughout the evening.", "Festive food: Traditional dishes from local cooks.", "For the children: Crafts, games and storytelling.", "The finale: A spectacle you will not want to miss."],
        { details: ["Date: Saturday evening", "Time: From 5:00 pm", "Venue: Town Square Gardens", "Entry: Free for all"], themes: OCCASIONS }),
      sub("invitation", "Invitation", "event", "invitation, invite, rsvp, party, occasion",
        ["You're invited", "Please join us", "An evening to remember"],
        ["We are gathering our favourite people, and it would not be the same without you.", "Dinner, drinks and good conversation await."],
        ["Accept invitation", "RSVP"],
        ["Arrival: Welcome drinks from seven.", "Dinner: A seasonal menu served at eight.", "Dress: Smart, with room to dance.", "Plus one: You are welcome to bring a guest."],
        { details: ["Date: Saturday 20 September", "Time: 7:00 pm", "Venue: The Glasshouse", "RSVP by: 10 September"] }),
    ],
  },
  {
    slug: "social", name: "Social", description: "Creator, community and social campaign emails",
    brands: ["THE DAILY DRAFT", "STUDIO NOTES", "OPEN HOUSE", "SIDE PROJECT CLUB", "GOOD COMPANY", "AFTER HOURS"],
    prices: ["Free", "$5", "$12", "$40"],
    subs: [
      sub("creator-newsletter", "Creator Newsletter", "newsletter", "creator, newsletter, personal, writer, substack, weekly",
        ["Notes from the studio", "This week I learned", "Five things worth your time"],
        ["A weekly letter on making things, sharing them and staying sane.", "Short, honest and written by a person."],
        ["Read this week's issue", "Share with a friend"],
        ["The essay: Why finishing matters more than starting.", "Behind the scenes: What I am working on right now.", "Worth a click: Three links I kept coming back to.", "From the inbox: Your replies to last week's question."]),
      sub("community-update", "Community Update", "newsletter", "community, members, update, group, forum",
        ["What's new in the community", "Community round-up", "Your monthly member update"],
        ["New members, popular threads and what is coming up next.", "The best of what you all shared this month."],
        ["Visit the community", "Join the conversation"],
        ["Welcome to new members: Two hundred people joined us this month.", "Top discussions: The threads everyone is talking about.", "Member spotlight: A project that deserves your attention.", "Coming up: Events, challenges and live calls."]),
      sub("social-campaign", "Social Campaign", "announcement", "social media, campaign, hashtag, share, challenge",
        ["Share your story", "Join the challenge", "Tag us and take part"],
        ["Post your entry with our hashtag for a chance to be featured.", "A month-long challenge, open to everyone."],
        ["Take part", "See the entries"],
        ["How it works: Post, tag and share in three steps.", "The prizes: Features, gifts and a grand prize.", "The rules: Simple, fair and open to all.", "The deadline: Entries close at the end of the month."]),
      sub("influencer-campaign", "Influencer Campaign", "product", "influencer, creator, collaboration, partnership, ambassador",
        ["We'd love to work with you", "Become a brand partner", "A collaboration made for your audience"],
        ["We admire what you make, and we think your audience would love this.", "Paid partnerships, creative freedom and products you will actually use."],
        ["Apply to partner", "See the brief"],
        ["What you get: A fair fee and products to keep.", "What we ask: Honest content in your own voice.", "Creative freedom: You know your audience best.", "Timeline: Four weeks from brief to going live."]),
    ],
  },
  {
    slug: "education", name: "Education", description: "Schools, courses and learning communities",
    brands: ["BRIDGEWATER ACADEMY", "OPEN CLASSROOM", "MAPLE HILL SCHOOL", "LEARNWELL", "ST. EDMUND'S COLLEGE", "FIRST PRINCIPLES"],
    prices: ["Free", "$49", "$199", "$480"],
    subs: [
      sub("course-announcement", "Course Announcement", "product", "course, enrol, learning, online course, training",
        ["Enrolment is now open", "A new course starts soon", "Learn a new skill this term"],
        ["Eight weeks, practical projects and feedback from working professionals.", "Built for beginners, useful for everyone."],
        ["Enrol today", "View the syllabus"],
        ["Learn at your pace: Lessons you can fit around work.", "Real projects: Build a portfolio as you learn.", "Expert tutors: Feedback from people who do this for a living.", "Certificate: Proof of what you have achieved."]),
      sub("student-newsletter", "Student Newsletter", "newsletter", "student, newsletter, campus, term, school news",
        ["Your weekly student bulletin", "This week on campus", "What's on this term"],
        ["Deadlines, events and opportunities in one place.", "Everything you need to know before Monday."],
        ["Read the bulletin", "See all events"],
        ["Deadlines: Coursework due dates and exam timetable.", "Clubs and societies: New groups looking for members.", "Careers: Internships, talks and CV clinics.", "Wellbeing: Support is available all year round."]),
      sub("online-class", "Online Class", "event", "online class, lesson, live class, tutoring, virtual classroom",
        ["Your class starts soon", "Join the live lesson", "Class is in session"],
        ["Log in a few minutes early and have your notes ready.", "A live lesson with time for questions."],
        ["Join the class", "Add to calendar"],
        ["Before class: Read chapter three and note your questions.", "During class: Cameras on, microphones muted.", "After class: Slides and recording within the hour.", "Homework: A short exercise due next week."],
        { details: ["Date: Monday 3 March", "Time: 6:00 pm", "Platform: Live video classroom", "Tutor: Dr. Amara Osei"] }),
      sub("school-announcement", "School Announcement", "announcement", "school, parents, notice, announcement, term dates",
        ["A message for parents and carers", "Important school notice", "News from the headteacher"],
        ["Please take a moment to read the information below.", "Key dates and details for the coming weeks."],
        ["Read the notice", "View the calendar"],
        ["Term dates: The half-term break begins on the 24th.", "Parents' evening: Booking opens on Monday.", "School trips: Consent forms are due this week.", "Uniform: A reminder about the winter dress code."]),
      sub("university-newsletter", "University Newsletter", "newsletter", "university, alumni, research, campus, higher education",
        ["News from the university", "The alumni review", "Research, people and progress"],
        ["Stories from our students, staff and graduates around the world.", "A look at the discoveries and people shaping our community."],
        ["Read the stories", "Support our students"],
        ["Research spotlight: A breakthrough from the school of engineering.", "Alumni story: From lecture hall to launch pad.", "Campus news: The new library opens its doors.", "Get involved: Mentor a student this year."]),
    ],
  },
  {
    slug: "real-estate", name: "Real Estate", description: "Listings, viewings and development news",
    brands: ["HARLOW & FINCH", "KEYSTONE HOMES", "MERIDIAN ESTATES", "THE PROPERTY ROOM", "OAKFIELD LIVING", "CORNERSTONE"],
    prices: ["$385,000", "$520,000", "$749,000", "$1,250,000"],
    subs: [
      sub("property-listing", "Property Listing", "listing", "property, listing, for sale, home, house, apartment",
        ["Just listed", "A home worth seeing", "New to the market"],
        ["Light-filled rooms, a private garden and a ten-minute walk to the station.", "Homes like this rarely come up, and never stay long."],
        ["Book a viewing", "View the listing"],
        ["Three-bedroom townhouse: Period details with a modern kitchen.", "Garden apartment: Two bedrooms and a south-facing terrace.", "Family home: Four bedrooms near outstanding schools.", "City loft: Open-plan living with skyline views."]),
      sub("open-house", "Open House", "event", "open house, viewing, tour, property event",
        ["You're invited to our open house", "Open house this weekend", "Come and look around"],
        ["No appointment needed. Drop in, take the tour and meet the agent.", "See it in person and imagine yourself at home."],
        ["Register my visit", "Get directions"],
        ["Guided tours: Every half hour throughout the day.", "Meet the agent: Ask anything about the home and the area.", "Financing desk: Talk to a mortgage adviser on the spot.", "Refreshments: Coffee and pastries on us."],
        { details: ["Date: Saturday 17 May", "Time: 11:00 am to 3:00 pm", "Address: 42 Willow Crescent", "Guide price: $520,000"] }),
      sub("new-project", "New Project", "product", "new development, off-plan, launch, new build, apartments",
        ["A new address is coming", "Introducing a landmark development", "Register your interest today"],
        ["One, two and three-bedroom homes with gardens, a gym and a rooftop terrace.", "Designed by an award-winning practice and built to last."],
        ["Register interest", "Download the brochure"],
        ["Thoughtful design: Generous rooms and floor-to-ceiling windows.", "Life on your doorstep: Parks, cafes and transport within minutes.", "Residents' amenities: Gym, co-working lounge and roof garden.", "Built responsibly: Low-energy homes with green roofs."]),
      sub("property-alert", "Property Alert", "listing", "property alert, new listings, price drop, matches",
        ["New homes that match your search", "Price reduced on a home you viewed", "Fresh listings in your area"],
        ["We found new properties that fit what you are looking for.", "Updated this morning, so you see them first."],
        ["See all matches", "Update my search"],
        ["Price reduced: Now $25,000 below the original asking price.", "New today: Listed this morning in your chosen area.", "Back on the market: A second chance at a popular home.", "Coming soon: Register for early access."]),
    ],
  },
  {
    slug: "restaurant", name: "Restaurant", description: "Menus, bookings and food promotions",
    brands: ["OSTERIA LUNA", "THE COPPER POT", "SALT & EMBER", "GREEN TABLE", "LITTLE SAIGON KITCHEN", "BAKEHOUSE NO. 9"],
    prices: ["$9", "$14", "$22", "$38"],
    subs: [
      sub("menu", "Menu", "listing", "menu, dishes, restaurant, food, seasonal menu",
        ["Our new menu is here", "A taste of the season", "What's cooking this month"],
        ["Seasonal produce, cooked simply and served with care.", "New dishes from the kitchen, alongside the classics you love."],
        ["View the menu", "Book a table"],
        ["Wood-fired flatbread: Whipped ricotta, honey and thyme.", "Slow-braised short rib: Creamed polenta and charred greens.", "Market fish: Brown butter, capers and lemon.", "Dark chocolate tart: Sea salt and creme fraiche."]),
      sub("special-offer", "Special Offer", "promo", "restaurant offer, deal, lunch special, two for one, happy hour",
        ["Two courses for $22", "This week's special", "Dinner is on us (almost)"],
        ["Available Monday to Thursday. Booking recommended.", "A proper meal at a price that makes weeknights worth leaving the house for."],
        ["Book with this offer", "Claim the deal"],
        ["Lunch set: Two courses and a drink for $16.", "Happy hour: Half-price small plates from five to seven.", "Family feast: Sharing platters for four.", "Dessert on us: When you book for six or more."]),
      sub("reservation", "Reservation", "transactional", "reservation, booking confirmed, table, confirmation",
        ["Your table is booked", "Reservation confirmed", "We look forward to seeing you"],
        ["Everything is set. If your plans change, let us know and we will rearrange.", "Here are the details of your booking."],
        ["Manage my booking", "Get directions"],
        ["Arriving: We hold tables for fifteen minutes.", "Dietary needs: Tell us in advance and the kitchen will prepare.", "Celebrating?: Let us know and we will make it special.", "Parking: Free after six in the square opposite."],
        { details: ["Date: Friday 21 March", "Time: 7:30 pm", "Guests: 4 people", "Booking reference: LUNA-2281"] }),
      sub("food-promotion", "Food Promotion", "promo", "food, promotion, delivery, takeaway, new dish",
        ["Hungry? We deliver.", "A new favourite just landed", "Order tonight, eat in thirty minutes"],
        ["Freshly made and delivered hot to your door.", "Try the dish everyone is talking about."],
        ["Order now", "See the full menu"],
        ["The signature burger: Aged beef, smoked cheddar and house pickles.", "Crispy cauliflower bowl: Tahini, herbs and pickled chilli.", "Loaded fries: Slow-cooked brisket and three cheeses.", "Sticky toffee pudding: Because you deserve it."]),
      sub("festival-menu", "Festival Menu", "listing", "festival menu, festive, holiday menu, celebration, special menu",
        ["A festive menu to share", "Celebrate at our table", "Our special festival menu"],
        ["A feast of traditional favourites, made for sharing with family and friends.", "Available for a limited time. Book early to avoid disappointment."],
        ["Reserve a table", "View the festive menu"],
        ["To begin: A selection of small plates for the table.", "The feast: Slow-cooked mains with all the trimmings.", "Something sweet: Traditional desserts made in-house.", "To drink: Festive cocktails and spiced teas."],
        { themes: OCCASIONS }),
    ],
  },
  {
    slug: "travel", name: "Travel", description: "Offers, destinations and booking emails",
    brands: ["WAYFARE", "BLUE HORIZON", "ATLAS & CO", "THE SLOW ROAD", "HARBOUR HOTELS", "NORTH STAR TRAVEL"],
    prices: ["$149", "$399", "$899", "$1,650"],
    subs: [
      sub("travel-offer", "Travel Offer", "promo", "travel deal, holiday offer, flights, package, getaway",
        ["Your next escape, for less", "Holiday deals from $399", "Pack your bags"],
        ["Flights and hotels included, with flexible dates and free cancellation.", "Book by Sunday to lock in these prices."],
        ["See the deals", "Book my escape"],
        ["City breaks: Three nights in Europe's best small cities.", "Beach escapes: A week in the sun, all inclusive.", "Mountain retreats: Fresh air, big views and a hot tub.", "Last minute: Leave this weekend and save more."]),
      sub("hotel-promotion", "Hotel Promotion", "promo", "hotel, stay, rooms, spa, weekend break, resort",
        ["Stay three nights, pay for two", "A weekend you deserve", "Check in and switch off"],
        ["Breakfast in bed, a late checkout and a view worth waking up for.", "An offer for guests who book direct."],
        ["Check availability", "Book my stay"],
        ["The rooms: Linen sheets, rain showers and quiet.", "The spa: Pool, sauna and treatments on request.", "The restaurant: A kitchen garden menu that changes daily.", "The extras: Bikes, picnics and a boat to borrow."]),
      sub("destination", "Destination", "listing", "destination, guide, where to go, inspiration, itinerary",
        ["Where to go next", "A guide to the coast", "Four places worth the journey"],
        ["Our writers on the places they keep going back to.", "Good food, quiet beaches and the best time to visit."],
        ["Read the guide", "Plan my trip"],
        ["The old town: Narrow streets, late dinners and live music.", "The islands: A ferry ride to empty beaches.", "The hills: Vineyards, villages and long lunches.", "The coast road: A drive with a view at every turn."]),
      sub("booking-confirmation", "Booking Confirmation", "transactional", "booking confirmation, itinerary, reservation, trip details, e-ticket",
        ["You're all booked", "Your trip is confirmed", "Get ready to go"],
        ["Here is your itinerary. Keep this email handy when you travel.", "Everything you need for a smooth journey."],
        ["View my booking", "Download my itinerary"],
        ["Before you go: Check your passport and any entry requirements.", "At the airport: Arrive two hours before departure.", "Getting there: A transfer will meet you at arrivals.", "Need to change something?: Amend your booking online any time."],
        { details: ["Booking reference: WF-77K2Q", "Dates: 12 to 19 August", "Guests: 2 adults", "Total paid: $1,798"] }),
    ],
  },
  {
    slug: "technology", name: "Technology", description: "Product, release and developer emails",
    brands: ["STACKLINE", "ORBIT", "PATCHWORK", "QUANTA", "RELAY", "BASECAMP LABS"],
    prices: ["Free", "$12/mo", "$29/mo", "$99/mo"],
    subs: [
      sub("saas-launch", "SaaS Launch", "product", "saas, software, launch, app, startup, beta",
        ["Now in public beta", "The simplest way to run your workflow", "We just launched"],
        ["Set it up in minutes and never chase a status update again.", "Free while in beta, with every feature unlocked."],
        ["Start free", "See how it works"],
        ["Automations: Hand the repetitive work to the machine.", "Shared views: Everyone sees the same source of truth.", "Integrations: Connects to the tools you already use.", "Insights: Know what is slowing your team down."]),
      sub("feature-update", "Feature Update", "newsletter", "feature, update, release notes, improvements, changelog",
        ["New this month", "Fresh features, just shipped", "You asked, we built it"],
        ["The improvements you requested most, live in your account today.", "Small changes that add up to a faster day."],
        ["Try the new features", "Read the release notes"],
        ["Bulk editing: Change a hundred items in one go.", "Dark mode: Easier on the eyes after hours.", "Faster search: Results appear as you type.", "Mobile app: Approvals from wherever you are."]),
      sub("product-update", "Product Update", "newsletter", "product update, roadmap, what's new, version",
        ["Product update: what's new and what's next", "Version 4 is here", "A look at the roadmap"],
        ["A summary of recent releases and a preview of what we are building.", "Where the product is today, and where it is going."],
        ["See what's new", "View the roadmap"],
        ["Shipped: Six improvements that landed this month.", "In progress: What the team is building now.", "Up next: Planned for the coming quarter.", "Your feedback: Vote on what we tackle after that."]),
      sub("developer-newsletter", "Developer Newsletter", "newsletter", "developer, api, engineering, code, changelog, docs",
        ["The developer digest", "API updates and engineering notes", "What's new for builders"],
        ["New endpoints, SDK releases and things we learned shipping them.", "Written by engineers, for engineers."],
        ["Read the docs", "View the changelog"],
        ["API v3: Pagination, webhooks and better errors.", "SDK releases: TypeScript and Python clients updated.", "From the blog: How we cut build times by sixty percent.", "Community: Open-source projects built on our platform."]),
    ],
  },
  {
    slug: "finance", name: "Finance", description: "Financial news, markets and banking notices",
    brands: ["STERLING & VALE", "FIRST HARBOUR BANK", "LEDGERLINE", "CAPITAL NORTH", "OAKTREE WEALTH", "PENNYWISE"],
    prices: ["$0", "$9/mo", "$25/mo", "$250"],
    subs: [
      sub("financial-newsletter", "Financial Newsletter", "newsletter", "finance, markets, money, economy, weekly",
        ["Your weekly money briefing", "Markets in five minutes", "What moved, and why it matters"],
        ["A plain-English look at the week in markets and what it means for you.", "No jargon, no hype, just context."],
        ["Read the briefing", "See market data"],
        ["The big picture: What drove markets this week.", "Rates and inflation: The numbers to watch next.", "One chart: The trend worth understanding.", "Your money: A practical step to take this month."]),
      sub("investment-update", "Investment Update", "newsletter", "investment, portfolio, performance, fund, wealth",
        ["Your portfolio update", "Quarterly investment review", "How your investments performed"],
        ["Performance, positioning and our outlook for the months ahead.", "A summary from your investment team."],
        ["View my portfolio", "Read the full review"],
        ["Performance: How the portfolio did against its benchmark.", "Positioning: What we bought, sold and held.", "Outlook: The themes we expect to matter.", "Next steps: Book a review with your adviser."]),
      sub("banking-announcement", "Banking Announcement", "announcement", "bank, banking, account, notice, service update",
        ["An update to your account", "Changes to our services", "Important information from your bank"],
        ["You do not need to do anything, but we want you to know what is changing.", "Please read this notice about your account."],
        ["Review the changes", "Log in securely"],
        ["What is changing: Updated terms from the first of next month.", "What it means for you: No change to your everyday banking.", "Staying safe: We will never ask for your PIN by email.", "Need help?: Call us or visit your local branch."]),
    ],
  },
  {
    slug: "health", name: "Health & Wellness", description: "Clinics, fitness and wellbeing",
    brands: ["WELLSPRING", "THE BODY STUDIO", "GREENLEAF CLINIC", "STILLPOINT", "CORE & CALM", "BRIGHT SMILE DENTAL"],
    prices: ["Free", "$15", "$45", "$120"],
    subs: [
      sub("wellness-newsletter", "Wellness Newsletter", "newsletter", "wellness, health, wellbeing, self care, mindfulness",
        ["Small habits, big difference", "Your monthly wellness letter", "Feel better this week"],
        ["Evidence-based ideas for sleeping, eating and moving a little better.", "Simple, realistic and kind."],
        ["Read this month's letter", "Explore the guides"],
        ["Sleep: A wind-down routine that actually works.", "Move: Ten minutes that beat none at all.", "Eat: Three easy ways to add more plants.", "Mind: A two-minute breathing exercise."]),
      sub("appointment-reminder", "Appointment Reminder", "transactional", "appointment, reminder, clinic, booking, healthcare",
        ["A reminder about your appointment", "See you soon", "Your appointment is coming up"],
        ["If you can no longer attend, please let us know so we can offer the slot to someone else.", "Here are the details of your visit."],
        ["Confirm appointment", "Reschedule"],
        ["Before you arrive: Bring your ID and a list of any medication.", "On the day: Please arrive ten minutes early.", "Parking: Free for patients behind the building.", "Cannot make it?: Reschedule online in under a minute."],
        { details: ["Date: Tuesday 8 April", "Time: 10:20 am", "With: Dr. Lena Hartmann", "Location: Greenleaf Clinic, Room 4"] }),
      sub("fitness-promotion", "Fitness Promotion", "promo", "fitness, gym, membership, classes, training offer",
        ["Your first month, on us", "New year, new routine", "Join today and save 30%"],
        ["Unlimited classes, expert coaches and a community that shows up.", "No joining fee when you sign up this week."],
        ["Claim my free month", "View memberships"],
        ["Strength: Small-group coaching for every level.", "Cardio: High-energy classes that fly by.", "Recover: Yoga, mobility and a sauna.", "Coaching: A personal plan built around your goals."]),
      sub("clinic-announcement", "Clinic Announcement", "announcement", "clinic, practice, health service, opening hours, new service",
        ["Now offering weekend appointments", "A new service at our clinic", "An update from your practice"],
        ["We are extending our hours to make care easier to fit around your life.", "New practitioners, new services and the same friendly team."],
        ["Book an appointment", "Meet the team"],
        ["Extended hours: Open until eight on weekdays.", "New services: Physiotherapy and nutrition clinics.", "Online booking: Choose a time that suits you.", "Same-day care: Urgent appointments every morning."]),
    ],
  },
  {
    slug: "nonprofit", name: "Nonprofit", description: "Fundraising, impact and volunteering",
    brands: ["OPEN HANDS", "THE RIVER TRUST", "BRIGHT FUTURES FUND", "COMMON GROUND", "SEEDLING PROJECT", "NEIGHBOURS FIRST"],
    prices: ["$10", "$25", "$50", "$100"],
    subs: [
      sub("donation-appeal", "Donation Appeal", "announcement", "donation, appeal, fundraising, charity, give",
        ["Your gift changes everything", "Will you help today?", "Together we can do more"],
        ["Every contribution goes directly to the people who need it most.", "A small gift from you makes a real difference to someone else."],
        ["Donate now", "Give monthly"],
        ["$10 provides: School supplies for one child for a term.", "$25 provides: A week of meals for a family.", "$50 provides: Clean water for a household for a year.", "$100 provides: Training for a community health worker."]),
      sub("impact-report", "Impact Report", "newsletter", "impact, annual report, results, thank you, supporters",
        ["Look what you made possible", "Our year in impact", "Your support, in numbers"],
        ["A report on what your generosity achieved this year.", "Stories and results from the communities we serve."],
        ["Read the full report", "Share our story"],
        ["Lives reached: More families supported than in any previous year.", "Where the money went: Eighty-six cents of every dollar to programmes.", "A story from the field: One community, one year on.", "What comes next: Our goals for the year ahead."]),
      sub("volunteer-callout", "Volunteer Callout", "event", "volunteer, volunteering, community, help, sign up",
        ["We need your hands", "Volunteer with us this weekend", "Give a morning, make a difference"],
        ["No experience needed. Bring a friend and we will provide the rest.", "A few hours of your time goes a long way."],
        ["Sign up to volunteer", "See open roles"],
        ["What you will do: Sort, pack and deliver with the team.", "What to bring: Comfortable shoes and a water bottle.", "Who you will meet: Friendly people from your neighbourhood.", "What you will get: Lunch, thanks and a very good feeling."],
        { details: ["Date: Saturday 10 May", "Time: 9:00 am to 1:00 pm", "Meeting point: Community Hall, Elm Street", "Places: 40 volunteers"] }),
    ],
  },
];

export function allEmailSubcategories(): { category: CategoryDef; sub: SubcategoryDef }[] {
  return EMAIL_CATEGORIES.flatMap((category) => category.subs.map((sub) => ({ category, sub })));
}
