import React, { useEffect, useId, useMemo, useRef, useState } from "react";

interface TemplateThumbProps {
  /** URL of a template's SVG preview */
  src?: string;
  /** SVG preview markup (used for a user's own designs) */
  svg?: string | null;
  title: string;
  /** Classes for the area behind the preview; white suits emails, which are always light */
  backing?: string;
}

// Previews never change for a given URL, so each is fetched once per page visit
const cache = new Map<string, string>();

/**
 * Shows a template's SVG preview inline.
 *
 * The SVG is placed in the page itself rather than in an <img>, because an SVG
 * used as an image is not allowed to load other files, which would leave every
 * photo in it blank. Previews are generated by Falcon's own server from
 * escaped template content. They are fetched only once scrolled near.
 */
export default function TemplateThumb({ src, svg, title, backing = "bg-white" }: TemplateThumbProps) {
  const holder = useRef<HTMLDivElement>(null);
  const uid = useId().replace(/[^a-zA-Z0-9]/g, "");
  const [markup, setMarkup] = useState<string | null>(svg ?? (src ? cache.get(src) ?? null : null));

  useEffect(() => {
    if (svg) {
      setMarkup(svg);
      return;
    }
    if (!src) return;
    const cached = cache.get(src);
    if (cached) {
      setMarkup(cached);
      return;
    }
    const node = holder.current;
    if (!node) return;
    let cancelled = false;
    const observer = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting) return;
        observer.disconnect();
        fetch(src)
          .then((res) => (res.ok ? res.text() : Promise.reject(new Error("preview unavailable"))))
          .then((text) => {
            if (!text.startsWith("<svg")) return;
            cache.set(src, text);
            if (!cancelled) setMarkup(text);
          })
          .catch(() => undefined);
      },
      { rootMargin: "400px" }
    );
    observer.observe(node);
    return () => {
      cancelled = true;
      observer.disconnect();
    };
  }, [src, svg]);

  // Gradient and clip ids repeat between previews; prefix them so one card never borrows another's
  const html = useMemo(
    () => (markup ? markup.replace(/id="([a-z]\d+c?)"/g, `id="${uid}$1"`).replace(/url\(#([a-z]\d+c?)\)/g, `url(#${uid}$1)`) : ""),
    [markup, uid]
  );

  return (
    <div
      ref={holder}
      role="img"
      aria-label={title}
      data-theme-keep=""
      className={`h-full w-full overflow-hidden ${backing} [&>svg]:block [&>svg]:h-full [&>svg]:w-full`}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
